from setuptools import setup
setup(
    name="prithviwxc-gravitywave",  
    version="0.1.0",
    packages=["prithviwxc.gravitywave"],
    author="Sujit Roy",
    author_email="sr0197@uah.edu",
    description="Gravity Wave Parameterization",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/NASA-IMPACT/gravity-wave-finetuning",
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.11',
    install_requires=[
        "cachetools==5.5.0",
        "cartopy==0.23.0",
        "click==8.1.7",
        "cloudpickle==3.0.0",
        "contourpy==1.3.0",
        "cycler==0.12.1",
        "dask==2024.8.1",
        "docker-pycreds==0.4.0",
        "fonttools==4.53.1",
        "fsspec==2024.6.1",
        "gitdb==4.0.11",
        "gitpython==3.1.43",
        "h5netcdf==1.3.0",
        "h5py==3.11.0",
        "kiwisolver==1.4.7",
        "locket==1.0.0",
        "matplotlib==3.9.2",
        "nvidia-ml-py==12.535.161",
        "nvitop==1.3.2",
        "pandas==2.2.2",
        "partd==1.4.2",
        "platformdirs==4.2.2",
        "protobuf==5.27.3",
        "pyhelpme==0.1",
        "pyparsing==3.1.4",
        "pyproj==3.6.1",
        "pyshp==2.3.1",
        "python-dateutil==2.9.0.post0",
        "pytz==2024.1",
        "sentry-sdk==2.13.0",
        "setproctitle==1.3.3",
        "shapely==2.0.6",
        "smmap==5.0.1",
        "tabulate==0.9.0",
        "termcolor==2.4.0",
        "toolz==0.12.1",
        "tqdm==4.66.5",
        "tzdata==2024.1",
        "wandb==0.17.7",
        "xarray==2024.7.0",
        "yacs==0.1.8",
    ],
)
